name: Build with Submodule
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [subpage-updated]

jobs:
  build:
    permissions:
          pages: write
          id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout parent repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.3
          bundler-cache: true

      - name: Build with Jekyll
        run: |
          bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          folder: _site